workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 120

    environment:
      java: 17

    working_directory: JapaneseBot

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Grant Gradle permission
        script: |
          chmod +x gradlew || true

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
